### ISSUE TITLE
Mc Sales Promo - Parameter

### ISSUE THREAD

**Issue by gharvey1994** [mtcuison/GMC-MC-Warehouse#4]
Upon Update nag sasave po siya pero pag iloload ulit bumabalik sa dati hindi na update kapag 0 yung value ng term

![Screenshot 2022-12-16 133354](https://user-images.githubusercontent.com/119919514/208029599-0861527c-fe44-40f4-ae12-7f0203b5393a.png)

**Comment by mtcuison** [comment]
for re-testing. new dll nasa .230 ggcWarehouse.dll

thanks.
