### ISSUE TITLE
BNOS Classification

### ISSUE THREAD

**Issue by mtcuison** [mtcuison/GMC-MC-Warehouse#6]
Initial phase of BNOS Classification project wherein the 2H Officer will tag the Brand New Old Stock motorcycles with discounts and to be sold as BNOS. Below is a sample standard computation for BNOS units:

![image](https://github.com/mtcuison/GMC-MC-Warehouse/assets/77145878/0d695738-3b33-44dd-9afa-dec288fe8f8c)

The system to be used is the mcWIMS.

How to access the module?
- [ ] Transactions -> BNOS Classification for the entry/update
- [ ] Approval form is the same as the entry form
- [ ] Registers-> BNOS Classification for the history

![image](https://github.com/mtcuison/GMC-MC-Warehouse/assets/77145878/de71e46a-7c3e-4dea-9e54-8f7e8d5e310f)
![image](https://github.com/mtcuison/GMC-MC-Warehouse/assets/77145878/a1bd4c7b-d757-468f-8f22-9c15508b5832)
![image](https://github.com/mtcuison/GMC-MC-Warehouse/assets/77145878/423087fe-9d12-44a1-8280-fa068bd5ac79)

1. The units to be classified must be located on the 2H Warehouse and to be classified first before transferring to other 2H branch
2. Please note that the Brand New SRP is our SRP and the BNOS SRP will be the price if the unit will be tagged as BNOS.
3. Brand New SRP and BNOS SRP fields are locked
4. Min. Down will be the amount that the system will require on MC Sales as the Minimum Down
5. User can encode Serial ID/Engine No/Frame No to load a unit. This form can handle multiple items.
6. The discounting fields are Default Disc, Slow Moving Disc, By Price Disc
7. Check "With Issue 3K+" checkbox if the item has issue that costs 3000 pesos and above
8. Additional discounts are Issue Disc and the Adtl Disc Rate
9. Please note the the BNOS SRP is always rounded off to the nearest 100

What is the next step when the encoder saved the transaction?
1. Inform the 2H officer to approve the transaction encoded
2. 2H officer will approve/update/disapproved the transaction
3. After the 2H officer approves the transaction, the officer must inform M' Loraine to confirm the transaction on AR Sales System
4. Please go to BNOS Confirmation issue on [[Motocycle-Loan-Receivable-Tracker](https://github.com/mtcuison/Motocycle-Loan-Receivable-Tracker)](https://github.com/mtcuison/Motocycle-Loan-Receivable-Tracker/issues/3)
5. M' Loraine must confirm the transaction to tag the units as BNOS and ready to be sold using [[GMC-Integrated-Systems](https://github.com/mtcuison/GMC-Integrated-Systems)  ](https://github.com/mtcuison/GMC-Integrated-Systems/issues/4)

Affected tables are:
  MC_BNOS_Classify_Master
  MC_BNOS_Classify_Detail

Affected objects are compiled as:
  IntegSys.exe
  mcWIMS.exe
  mcLRTracker.exe
  ggcWarehouse.dll
  ggcMCSales.dll
  ggcPriceUpdate.dll

**Note:
   Only testers/implementers can will close this issue. Please close it immediately if issue was okay or comment on this issue right away for concerns. Do not create new issue within this issue.**

Thank you.

**Comment by jeraldjohncv** [comment]
Project ID: MCWIMS & LRTrckr
Project Name: Brand New Old Stock (BNOS) Classification			
Sub Name: Additional Features
Objective: Initial   phase of BNOS Classification project wherein the 2H Officer will tag the   Brand-New Old Stock motorcycles with discounts and to be sold as BNOS.

I.

Desktop   - MCWims // Encoding and saving of BNOS units for classification.
![image](https://github.com/mtcuison/GMC-MC-Warehouse/assets/133741456/609c8bce-5f9b-406a-8780-af3417d769d9)

- [x] upon saving of my entry, insufficient detail classification appeard. Pwede po ba na sabihin ng system kung ano yung kulang sa entry sa text box?

Desktop   - MCWims // Approval of classification by 2H officer
- [x] "encoder" can approve the classified transaction.

Desktop - MCWims // BNOS Classification Printing
- [ ]  ![image](https://github.com/mtcuison/GMC-MC-Warehouse/assets/133741456/d293c874-9b66-425e-9877-29f0c67f3b62)

Desktop - IntegSys
![image](https://github.com/mtcuison/GMC-MC-Warehouse/assets/133741456/eca6c852-8739-4a0f-b300-6151f8ea35d5)
![image](https://github.com/mtcuison/GMC-MC-Warehouse/assets/133741456/ac08174c-bbcc-4335-8c3c-870ea6d66267)
![image](https://github.com/mtcuison/GMC-MC-Warehouse/assets/133741456/88ceec05-10ee-4523-a241-34a329095e0c)
- [x] The SRP is not match for the approved classification.

**Comment by mtcuison** [comment]
Only supervisor account up can only approve.

![image](https://github.com/mtcuison/GMC-MC-Warehouse/assets/77145878/ccca2138-66d8-461c-aeac-07f5177b36fe)

**Comment by mtcuison** [comment]
"The SRP is not match for the approved classification."
 
 Please check if the transaction if posted. Unposted transactions will not reflect the price on MC Sales.

![image](https://github.com/mtcuison/GMC-MC-Warehouse/assets/77145878/7f646ac5-839a-475c-9b8f-fbe1e340029d)

**Comment by jeraldjohncv** [comment]
> Only supervisor account up can only approve.
> 
> ![image](https://user-images.githubusercontent.com/77145878/281967702-ccca2138-66d8-461c-aeac-07f5177b36fe.png)

- [ ] in this case sir, still. the encoder can approve the entry supposed to be not.

**Comment by jeraldjohncv** [comment]
Project ID: MCWIMS & LRTrckr
Project Name: Brand New Old Stock (BNOS) Classification
Sub Name: Additional Features
Objective: Initial phase of BNOS Classification project wherein the 2H Officer will tag the Brand-New Old Stock motorcycles with discounts and to be sold as BNOS.

II.

Desktop - MCWims // Encoding and saving of BNOS units for classification
- [x] upon saving of my entry, insufficient detail classification appeard. Pwede ba na sabihin ng system kung ano yung kulang sa entry sa text box?

Desktop   - MCWims // Approval of classification by 2H officer
- [x] ![image](https://github.com/mtcuison/GMC-MC-Warehouse/assets/133741456/5d614f2f-868e-4b85-893c-aab8cd041930)

Desktop   - MCWims // Unit discounts & computation
- [x] ratings can encode more than the maximum given criteria.

Desktop - IntegSys // MC Sales encoding & Saving of BNOS unit - Cash Balance
- [x] ![image](https://github.com/mtcuison/GMC-MC-Warehouse/assets/133741456/4471019d-fbb1-48c2-9622-c8f57418e1f8)

Desktop - IntegSys // Account Receivable computation of PN Value & Monthly Amort
- [x] hingi po ako ng magiging basis po sa computation.

**Comment by mtcuison** [comment]
for the issue of Desktop - IntegSys // MC Sales encoding & Saving of BNOS unit - Cash Balance

hende ko mabasa. pakiresend ng mas malaking screenshot


for the issue of Desktop - IntegSys // Account Receivable computation of PN Value & Monthly Amort

currently, the computation is same as the brand new rate. will set a meeting to mam loraine to confirm on what will be the standard rate of BNOS, including the 2H.

please get the updated mcWIMS.exe and ggcWarehouse.dll @ 192.168.10.254

**Comment by jeraldjohncv** [comment]
Desktop - IntegSys // MC Sales encoding & Saving of BNOS unit - Cash Balance
- [x] ![image](https://github.com/mtcuison/GMC-MC-Warehouse/assets/133741456/0ae4535d-4f5f-44e9-9e78-94f43f2191c4)

ps. copy po sir, re-test ko nalang po ito. thank you.

**Comment by mtcuison** [comment]
Desktop - IntegSys // MC Sales encoding & Saving of BNOS unit - Cash Balance

pakikuha yung updated na 

ggcMCSales
ggcPriceUpdate
ggcLoanReceivable
ggcClients

sa .254 parekoy. nagcontinue na saving wala pero akong ginalaw sa block ng code na nakaindicate sa issue, sa .224 ako nagtest.

![Screenshot 2023-11-21 093739](https://github.com/mtcuison/GMC-MC-Warehouse/assets/77145878/e14ae2cf-e690-4db1-ab62-719524323315)
![Screenshot 2023-11-21 093820](https://github.com/mtcuison/GMC-MC-Warehouse/assets/77145878/ab1441bf-d9f5-414e-baa7-82b196714ff5)
![image](https://github.com/mtcuison/GMC-MC-Warehouse/assets/77145878/f15058f0-89dd-4b4e-99d3-d561b02b4dbc)
